In [1]:
# NUMPY -- NUMERICAL PYTHON

import numpy as np
print(np.__version__)

# numpy provides the support for a very powerful data structure -- ARRAY
# numpy array is been denoted by using []
# array() --> used to create 1D and 2D array

arr = np.array([10,20,30,40])
print(type(arr))
print(arr)

2.0.2
<class 'numpy.ndarray'>
[10 20 30 40]


In [2]:
# Numpy vs List

# print the sum of List Elements

numbers = [1, 2, 3, 4, 5]
total = 0

for n in numbers:
  total += n

print(total)


15


In [3]:
# using numpy

numbers = np.array([1,2,3,4,5])
print(np.sum(numbers))

15


In [4]:
# In Numpy Speed Is Better

import time

numbers = list(range(1,10000001))
total = 0

start_time = time.time()     # provide some start time
for n in numbers:
  total += n
end_time = time.time()     # provide some end time

print(total)
print(f"Total Time Taken : {end_time-start_time:.4f}")

50000005000000
Total Time Taken : 1.3906


In [5]:
# using numpy

numbers = np.arange(1,10000001,dtype=np.int64)

start_time = time.time()     # provide some start time
print(np.sum(numbers))
end_time = time.time()     # provide some end time

print(f"Total Time Taken : {end_time-start_time:.4f}")

50000005000000
Total Time Taken : 0.0096


In [6]:
# Array

# In programming Array is a data structure [collection of data elements]

# Array is denoted by using []

# Array is a collection of similar data types

list1 = [10,78.21,"Python",True]

print(list1)

arr = np.array([10,78.21,"Python",True])  # smaller data types will be converted to higher data type (STR -- FLOOT -- INT -- BOOL)

print(arr)

[10, 78.21, 'Python', True]
['10' '78.21' 'Python' 'True']


In [7]:
# array() --> used to create 1D and 2D array
# 1D Array

arr = np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [8]:
# if you are using a property : propertyname
# if you are using a method : methodname()

In [9]:
# shape property
# help us to determine the dimension of an array

# for 1D array shape property returns n,
# where n is the number of elements

# for 2D array shape property returns n,m
# where n is the number of rows and m is the number of columns

print(arr.shape) # or -- print(np.array([10,20,30,40,50,60]).shape)

(6,)


In [10]:
# 2D Array

# here we will store the elements in row column format

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print()

# Task
# 3x4
arr = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
print(arr.shape)
print()

# 5x2
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

(3, 4)

(5, 2)


In [11]:
# Numpy Array Is A Sequence + Iterable
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr)

# Indexing And Slicing
print(arr[0])
print(arr[-1])
print(arr[::-1])
print(arr[1:5])

[ 10  20  30  40  50  60  70  80  90 100]
10
100
[100  90  80  70  60  50  40  30  20  10]
[20 30 40 50]


In [12]:
for i in enumerate(arr):
  print(i)

(0, np.int64(10))
(1, np.int64(20))
(2, np.int64(30))
(3, np.int64(40))
(4, np.int64(50))
(5, np.int64(60))
(6, np.int64(70))
(7, np.int64(80))
(8, np.int64(90))
(9, np.int64(100))


In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

'''
    c0    c1   c2
ro   1    2     3              0,0    0,1  0,2
r1   4    5     6              1,0    1,1  1,2
r2   7    8     9              2,0    2,1  2,2

'''

print(arr[2,1])
print(arr[0,2])

# print only first row
print(arr[0])    # 1 2 3

# print only third row
print(arr[2])    # 1 2 3

# print only second column
# syntax  arr[:column]  for column only use comma before indexNumber
print(arr[:,1])

# print only third column
print(arr[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
3
[1 2 3]
[7 8 9]
[2 5 8]
[3 6 9]


In [14]:
# NUMPY data types
# dtype property
# this property help us to determine the data type of an array

# int
arr = np.array([45,65,120,78,11,89])
print(arr.dtype)

arr = np.array([45,65,120,78,11,89],dtype='int8')   # int8 --> 8bits  int32 --> 32bits   int64 --> 64bits
print(arr.dtype)

marks = np.array([45,65,100,78,11,89],dtype='int8')
print(marks.dtype)


int64
int8
int8


In [15]:
arr = np.array([45.3,65.5,120.21,78.7,11.12,89.78])
print(arr.dtype)

arr = np.array([True,False,True])
print(arr.dtype)

arr = np.array(["Python", "Is", "Fun"])   # Unicode String
print(arr.dtype)

arr = np.array(["Python", "Programming", "Is", "Fun"])   # Unicode String
print(arr.dtype)

float64
bool
<U6
<U11


In [16]:
# astype() method
# in numpy astype() used to convert one data type into another data type

arr = np.array([45,65,120,78,11,89])
print(arr.dtype)

arr = arr.astype('float')
print(arr.dtype)
print(arr)

int64
float64
[ 45.  65. 120.  78.  11.  89.]


In [17]:
arr = np.array([45.3,65.5,120.21,78.7,11.12,89.78])
print(arr.dtype)

arr = arr.astype('int')
print(arr.dtype)
print(arr)

float64
int64
[ 45  65 120  78  11  89]


In [18]:
arr = np.array([45.3,65.5,120.21,78.7,11.12,89.78],dtype='i')
print(arr.dtype)

int32


In [19]:
# copy() vs view()

arr = np.array([45,65,120,78,11,89])
print("Ori Array",arr)

# copy()
# create the copy of an array in a different memory location

copied_arr = arr.copy()
print ("Copied Array" ,copied_arr)

print()
# if you make any changes in copied_array it won't affect the original array

copied_arr[0] = 450
print("Copied Array",copied_arr)
print("Ori Array",arr)

print()
# if you make any changes in copied_array it won't affect the copied array

arr[3] = 780
print("Ori Array",arr)
print("Copied Array",copied_arr)

Ori Array [ 45  65 120  78  11  89]
Copied Array [ 45  65 120  78  11  89]

Copied Array [450  65 120  78  11  89]
Ori Array [ 45  65 120  78  11  89]

Ori Array [ 45  65 120 780  11  89]
Copied Array [450  65 120  78  11  89]


In [20]:
# copy() vs view()

arr = np.array([45,65,120,78,11,89])
print("Ori Array",arr)

# view()
# is the representation of the original array
# it shares the same memory location

copied_arr = arr.view()
print ("Copied Array" ,copied_arr)

print()
# if you make any changes in copied_array it will affect the original array

copied_arr[0] = 450
print("Copied Array",copied_arr)
print("Ori Array",arr)

Ori Array [ 45  65 120  78  11  89]
Copied Array [ 45  65 120  78  11  89]

Copied Array [450  65 120  78  11  89]
Ori Array [450  65 120  78  11  89]


In [21]:
# show me the proof
# view()
# is the representation of the original array
# it shares the same memory location

arr = np.array([45,65,120,78,11,89])
copied_arr = arr.view()

# share_memory() --> returns TRUE if arrays are sharing same memory location

print(np.shares_memory(arr,copied_arr))

True


In [22]:
# Numpy Array Reshaping --> Converting 1D into 2D or 2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)  # 2x6   6x2   3x4   4x3   1x12    12x1

twod = arr.reshape(4,3)
print(twod)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr.shape)  # 13x1   1x13

twod = arr.reshape(1,13)
print(twod)
print(twod.shape)

(13,)
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]]
(1, 13)


In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# numpy.newaxis
# is used to increase the dimension of the existing array by adding
# one more dimension to it.
# 1D array will become 2D array

# arr[row:column]

arr[:,np.newaxis]   # Column Vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [25]:
arr[np.newaxis,:]   # Row Vector

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [26]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13]])
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]]


In [27]:
#  2D into 1D
twod = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod)
print(twod.shape)

print()

arr = twod.reshape(9)
print(arr)

# or

arr = twod.reshape(-1)
print(arr)

# or

arr = twod.flatten()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
# concatenate()

# used to join 2 arrays

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9,10])

arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8],[9,10]])

arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [30]:
# array_split()

arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.array_split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [31]:
# Sorting

# np.sort()   # by default ascending order

prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices))

[ 12  34  34  34  56  67  78  90  95 102 120 172]


In [32]:
# np.sort()[::-1]   # for descending order

prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices)[::-1])

[172 120 102  95  90  78  67  56  34  34  34  12]


In [33]:
# filter and Searching In Numpy

arr = np.array([1,4,2,7,9,3,5,8])
arr>=5 # Boolean Masking

array([False, False, False,  True,  True, False,  True,  True])

In [34]:
arr[arr>=5]

array([7, 9, 5, 8])

In [35]:
arr = np.array([1,4,2,7,9,3,5,8])
arr = arr[arr>=5]   # Boolean Masking
print(arr)

[7 9 5 8]


In [36]:
arr = np.array([1,4,2,7,9,3,5,8,12,14,13,9,6,5,11,7])
# not divisibe by 2
arr%2!=0

array([ True, False, False,  True,  True,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True])

In [37]:
arr = arr[arr%2!=0]
print(arr)

[ 1  7  9  3  5 13  9  5 11  7]


In [38]:
arr = np.array([1,4,2,7,9,3,5,8,12,14,13,9,6,5,11,7])

# not divisibe by 2 and should be greater than 7

# In  Python Numpy We Can Not Use and
# so for and you should use '&'

arr = arr[arr%2!=0]
arr = arr[arr>=7]
print(arr)

[ 7  9 13  9 11  7]


In [39]:
arr = arr[(arr%2!=0) & (arr>=7)]
print(arr)

[ 7  9 13  9 11  7]


In [40]:
# np.where(exprsn)
# np.where returns IndexNumbers

arr = np.array([1,4,2,7,9,3,5,8,12,14,13,9,6,5,11,7])
res = np.where((arr%2!=0) & (arr>=7))
print(arr[res])
print("Index Numbers:",res)



[ 7  9 13  9 11  7]
Index Numbers: (array([ 3,  4, 10, 11, 14, 15]),)


In [41]:
arr = np.array([1,4,2,7,9,3,5,8])
res = np.where(arr>=5)
print(arr[res])

[7 9 5 8]


In [42]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])

# Find indices where value is 30

indices = np.where(arr == 30)

print(f"Indices where value is 30: {indices}")

# Find indices where values are even

even_indices = np.where(arr % 2 == 0)

print(f"Indices of even values: {even_indices}")

# Conditional selection

new_arr = np.where(arr > 40, arr * 2, arr)

print(f"Array after conditional selection: {new_arr}")



Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [43]:
# Numpy Random Module

from numpy import random
x = random.randint(100)
print(x)

53


In [44]:
x = random.randint(100,150)
print(x)

100


In [45]:
# 1D

arr = random.randint(30,70, size=(10))
print(arr)

[61 67 43 64 32 66 57 35 41 53]


In [46]:
# 2D

arr = random.randint(100, size=(3,4))
print(arr)

[[67 25  5 53]
 [63 58 98 73]
 [99 43 73 89]]


In [47]:
# rand()
# generate a random float value between 0 and 1

x = random.rand()
print(x)

0.05070418575471358


In [48]:
# create 1D array using rand()

x = random.rand(10)
print(x)

[0.30607154 0.10802511 0.04634969 0.20009479 0.24336214 0.40367432
 0.81469112 0.07056429 0.20549009 0.10585764]


In [49]:
# create 2D array using rand()

x = random.rand(3,4)
print(x)

[[0.21668722 0.47685361 0.01615145 0.60055393]
 [0.81063916 0.00870845 0.46743669 0.55804445]
 [0.35110509 0.53781573 0.0067054  0.03694939]]


In [50]:
# The choice() method allows you to generate a random value
# based on array of values

x = random.choice([3,5,7,9])
print(x)

7


In [51]:
x = random.choice([3,5,7,9], size=(12))
print(x)

[3 7 7 3 7 9 3 7 3 9 3 3]


In [52]:
x = random.choice([3,5,7,9], size=(3,4))
print(x)

[[7 9 7 5]
 [9 3 7 7]
 [5 7 5 9]]


In [53]:
# numpy.zeros()
# this function allows us to create an array filled with Zeros 0
# default data type will be Float

arr = np.zeros(12)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [54]:
arr = np.zeros((3,3),dtype='i')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
# numpy.ones()
# this function allows us to create an array filled with Ones 1
# default data type will be Float

arr = np.ones(12)
print(arr)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [56]:
arr = np.ones((3,3), dtype='i')
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [57]:
# numpy.sum()
# used to compute the sum of all elements

x = np.random.randint(50, size=(12))
print(x)
print(np.sum(x))

[31 11 45 41  8 22 13 14 21 42 35 47]
330


In [58]:
# numpy.mean()
# mean value is the average value

x = np.random.randint(50, size=(12))
print(x)
print(np.mean(x))

[ 4 22 28 31 28  5 22 13 44 24 23  3]
20.583333333333332


In [59]:
# mode()
# the mode is the value that appears most number of times

from scipy import stats
x = np.random.randint(50,size=(12))
print(x)
print(stats.mode(x))

[41 11 39 12  3 21 27 15 11  1 15 45]
ModeResult(mode=np.int64(11), count=np.int64(2))


In [60]:
# numpy.unique()

# return unique elements as a sorted array

a = np.unique([1,2,3,4,5,1,2,3,6,7,8,5,6,7,8,11,10,15,10,11,13,14,6])

print(a)

# Expected Output : [ 1  2  3  4  5  6  7  8 11 10 15 13 14]

# Return          : [ 1  2  3  4  5  6  7  8 10 11 13 14 15]  --> dublicate remove but by default it rearrange the number, we don't want it. need to sort back using next code


[ 1  2  3  4  5  6  7  8 10 11 13 14 15]


In [61]:
arr = np.array([1,2,3,4,5,1,2,3,6,7,8,5,6,7,8,11,10,15,10,11,13,14,6])
uv , i = np.unique(arr,return_index=True)
print(uv) # unique_values
print(i) # index Numbers

[ 1  2  3  4  5  6  7  8 10 11 13 14 15]
[ 0  1  2  3  4  8  9 10 16 15 20 21 17]


In [62]:
# argsort --> reorder based on original appearance
uv[np.argsort(i)]

# [ 1  2  3  4  5  6  7  8 10 11 13 14 15]
# [ 0  1  2  3  4  8  9 10 16 15 20 21 17]

# re order --> [ 0  1  2  3  4  8  9 10 15 16 17 20 21]

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 10, 15, 13, 14])

In [63]:
arr = np.array([1,2,3,4,5,1,2,3,6,7,8,5,6,7,8,11,10,15,10,11,13,14,6])
uv , i = np.unique(arr,return_index=True)
uv[np.argsort(i)]

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 10, 15, 13, 14])

In [64]:
# arange()

print(np.arange(11))
print(np.arange(1,11))
print(np.arange(1,11,2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [65]:
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [66]:
x = np.arange(1,13).reshape(4,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [71]:
# Numpy Broadcasting

arr1 = np.array([5,8,10,12])
arr2 = np.array([3,7,6,5])

print(arr1+arr2)
print(arr1*arr2)

[ 8 15 16 17]
[15 56 60 60]


In [70]:
# Broadcasting is an error
# and this error will shown up
# when we perform arithmetic operation b/w uncompatible shapes

arr1 = np.array([5,8,10,12])
arr2 = np.array([3,7])

print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [69]:
# General Rules To Avoid Broadcasting

# a.) both array dimensions should be equal
# b.) if any of them is 1

arr1 = np.array([5,8,10,12])
arr2 = np.array([3])

print(arr1+arr2)

[ 8 11 13 15]
